"use runtime";

// TypeofGenerator - re-exports the typeof generation from JSValueGenerator
import { JSValueGenerator } from "../core/jsvalue.js";

export class TypeofGenerator {
    constructor(vm) {
        this.vm = vm;
    }

    generate() {
        // The actual _js_typeof is generated by JSValueGenerator.generateTypeof()
        // This class is a thin wrapper to satisfy the runtime's expectations
        // The real work is done when JSValueGenerator is instantiated
    }
}
